// <auto-generated />
using System;
using DewJUnit2MVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DewJUnit2MVC.Migrations
{
    [DbContext(typeof(CustContext))]
    partial class CustContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DewJUnit2MVC.Models.Customer", b =>
                {
                    b.Property<int?>("CustID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("CustID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustID = 1,
                            Name = "John Doe",
                            Password = "tacosauce3000",
                            Username = "AnonyMouse"
                        },
                        new
                        {
                            CustID = 2,
                            Name = "Solomon Batman",
                            Password = "batfamWebtoon",
                            Username = "DCgothboy"
                        },
                        new
                        {
                            CustID = 3,
                            Name = "Sally Acorn",
                            Password = "KenPenderIsAHack",
                            Username = "DenimVest"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
